### ISSUE TITLE
[Implementation] Trivy scanning of keycloak java dependencies

### ISSUE THREAD

**Issue by idunbarh** [CISA-SBOM-Community/SBOM-Generation#16]
## Objective

- Create a workflow that will generate an initial SBOM using Trivy thats based on [keycloak](https://github.com/keycloak/keycloak) source code.
- Future work will add metadata, enrich this SBOM, and validate completeness

## Recommendations

- [ ] Create a `.github/workflows/phase_1_keycloak.yml` workflow file.
- [ ] Do a shallow clone or download released source from latest keycloak release.
- [ ] Generate both SPDX and CycloneDX SBOMs using trivy.
  - ```
    # Example commands
    trivy fs keycloak/pom.xml   --skip-update --offline-scan --format cyclonedx --output sboms/trivy.java.cdx.json
    trivy fs keycloak/pom.xml   --skip-update --offline-scan --format spdx-json --output sboms/trivy.java.spdx.json
    ```
- [ ] "Stub" next stage to make it easy for the next person to help

## Additional Actions

- [ ] Determine how to scan all `pom.xml` files and not just top level
- [ ] Determine what should happen with javascript dependencies

**Comment by douglasdennis** [comment]
If nobody has volunteered yet for this task then I'd like to throw my hat in the ring to complete it.

**Comment by vpetersson** [comment]
@douglasdennis Great! I would recommend that we follow the same blueprint as outlined [here](https://github.com/CISA-SBOM-Community/SBOM-Generation/pull/4/files#diff-45c71567474db8771efd8e6dd8a28dfdf74b2ffa4c71ae5de185948b577b4eba) so that they are consistent between examples. At least big picture.
