### ISSUE TITLE
Decide on tool for generating hierarchical SBOMs  

### ISSUE THREAD

**Issue by vpetersson** [CISA-SBOM-Community/SBOM-Generation#22]
As discussed in #17, we need a way to create a hierarchical SBOM that can point to an application and container SBOM. This is a requirement for Phase 1 (Python), but also for Phase 2.

`sbomasm` and `bomctl` are candidates for this.

**Comment by nishakm** [comment]
I demo'd a workflow for this a long long time ago: https://github.com/vmware-archive/containers-with-sboms
It mostly uses buildah and tern, but it should work for any sbom generation tool. It still requires buildah to do the container stuff.

**Comment by vpetersson** [comment]
We decided to scrap the hierarchical SBOMs as the acceptance criteria for this Tiger Team. There's code for doing this with CycloneDX in a PR, but it was removed since we couldn't (easily) make it work for both CycloneDX and SPDX.

**Comment by vpetersson** [comment]
> I demo'd a workflow for this a long long time ago: https://github.com/vmware-archive/containers-with-sboms It mostly uses buildah and tern, but it should work for any sbom generation tool. It still requires buildah to do the container stuff.

Vagrant! That's a blast from the past :)

Nice one. It does however seem like [tern](https://github.com/tern-tools/tern) has been more or less abandoned though.

**Comment by nishakm** [comment]
> It does however seem like [tern](https://github.com/tern-tools/tern) has been more or less abandoned though.
Not abandoned. But everyone uses [syft](https://github.com/anchore/syft) anyway, so there is no incentive to contribute here.

**Comment by nishakm** [comment]
> We decided to scrap the hierarchical SBOMs as the acceptance criteria for this Tiger Team. There's code for doing this with CycloneDX in a PR, but it was removed since we couldn't (easily) make it work for both CycloneDX and SPDX.

Doesn't bomctl do this?

**Comment by vpetersson** [comment]
> > We decided to scrap the hierarchical SBOMs as the acceptance criteria for this Tiger Team. There's code for doing this with CycloneDX in a PR, but it was removed since we couldn't (easily) make it work for both CycloneDX and SPDX.
> 
> 
> 
> Doesn't bomctl do this?

Not to my knowledge, but @idunbarh can confirm.

**Comment by nishakm** [comment]
> > > We decided to scrap the hierarchical SBOMs as the acceptance criteria for this Tiger Team. There's code for doing this with CycloneDX in a PR, but it was removed since we couldn't (easily) make it work for both CycloneDX and SPDX.
> > 
> > 
> > Doesn't bomctl do this?
> 
> Not to my knowledge, but @idunbarh can confirm.

I guess [not yet](https://github.com/bomctl/bomctl/issues/81).
