### ISSUE TITLE
[Discussion] Include multiple creation tools in final SBOM?

### ISSUE THREAD

**Issue by tiegz** [CISA-SBOM-Community/SBOM-Generation#44]
Currently the workflows generate these list of SBOM creation tools for CycloneDX and SPDX, respectively:

```
{
  "metadata": {
    "tools": {
      "components": [
        {
          "type": "application",
          "group": "aquasecurity",
          "name": "trivy",
          "version": "0.54.1"
        }
      ]
    },
  }
}
```

SPDX:
```
  "creationInfo": {
    "creators": [
      "Organization: aquasecurity",
      "Tool: trivy-0.54.1",
      "Person: CISA Tiger Group for SBOM Generation Reference Implementations ()"
    ],
```

The specs describe these fields as:
* CycloneDX: `The tool(s) used to create the BOM`
* SPDX: `Identify who (or what, in the case of a tool) created the SPDX document.. If multiple participants or tools were involved, use multiple instances of this field.`

If we're going through the effort to denote how the SBOM was generated, should we include all 3 tools in that field (trivy, sbomasm, parlay w/ ecosystems)?

One possible way is to swap the Augment and Enrich steps, assuming that sbomasm can handle multiple creators.

**Comment by riteshnoronha** [comment]
Yes this is a good idea.  I raised a similar discussion  https://github.com/CISA-SBOM-Community/SBOM-Generation/discussions/45

`sbomasm` does support multiple edits for any array fields. e.g

```sh
sbomasm edit -a --subject document --tool 'trivy (0.56.1)'  --tool 'parlay (0.5.1)' --tool 'bomctl (v0.4.1)' photon.spdx.json  | fx 
```

```json
 "creationInfo": {
  "licenseListVersion": "3.19",
  "creators": [
   "Tool: tern-b8e13d1780cd3a02204226bba3d0772d95da24a0",
   "Tool: trivy (0.56.1)",
   "Tool: parlay (0.5.1)",
   "Tool: bomctl (v0.4.1)"
  ],
  "created": "2023-01-12T22:06:03Z"
 }, 
```

**Comment by riteshnoronha** [comment]
Sure let me give it a shot. Gimme till EOW.
